sudo: false
notifications:
  email: false
language: c
compiler: gcc
env:
  global:
    - PACKAGE=vcontrold
  matrix:
    - SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05.1/ramips/rt305x/OpenWrt-SDK-15.05.1-ramips-rt305x_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
install:
- mkdir -p $TRAVIS_BUILD_DIR/local ; cd $TRAVIS_BUILD_DIR/local
- wget "http://us.archive.ubuntu.com/ubuntu/pool/main/c/ccache/ccache_3.1.6-1_amd64.deb"
- dpkg -x *.deb .
- mkdir -p $TRAVIS_BUILD_DIR/cache ; cd $TRAVIS_BUILD_DIR/cache
- wget -c $SDK_URL
- mkdir -p $TRAVIS_BUILD_DIR/sdk ; cd $TRAVIS_BUILD_DIR/sdk
- export FILE=$TRAVIS_BUILD_DIR/cache/$(basename $SDK_URL)
- file $FILE
- tar xjf $FILE
- cd $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*
- mkdir package/$PACKAGE
- ln -s $TRAVIS_BUILD_DIR/Makefile package/$PACKAGE/
- ln -s $TRAVIS_BUILD_DIR/files package/$PACKAGE/
script:
- export PATH=$TRAVIS_BUILD_DIR/local/usr/bin:$PATH
- cd $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*
- ./scripts/feeds update packages >/dev/null
- ./scripts/feeds install -d m libxml2
- make V=s
- find $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*/bin/
- find . -name *controld_*.ipk -exec cp {} $TRAVIS_BUILD_DIR \;
before_deploy:
  git fetch --tags
deploy:
  provider: releases
  api_key:
    secure: SDfdkz+78hMCAMP9sYhxPUSyDFHifdESWzZvXQC6fAgjaNWYmjvd0bXRSZ6UReUTAsbKNrtsUcdiJ8Vl0+jzaQpU4aTNsxiyjCeBYgqWSnK5rZmXLIawGFs45DRNGuXcu3bpVvhsbYsur0ZIQpAX6Av6Db4QuNbZ0xWueLoHb+YU0cSL50okizo5yhRq7km1ZLIgd3J0W8z7jixj3hx58MHlBaRGhN1TCWKdqKMi1MSm2sWZTNz9eaKwNE/oJ8TQRQ3vynZ2HdHsKpZYk4WlWrdqzF5oBuYwnxQAV64bOFAJeNkoUukf0apZGrSSR/L+ouBTEVUxSluTZJ94RE9j+ICoDk08eaIhBib2Ryw1AO+DinAWuT2hHlIlOd7yQZVcv/1Jo77zZg++WbIJzCw8XY984UzVV6XLsbcx6rODrq3cclT2QaFaSxXKp7z4a2ZoBatoM3bMqb2aQ3c3j4A39NusBpnlbmO9plf6TgivBzs/r83g9oYzXVl8DSR4UXCGIRSlY41qmqtwCzf+rWkd560nbbKlMuwShiqlar//ios4SHG83zqkr/AwW3ljUEjXlwG81XK+DTHLlIEFYoMoUQD1YqkZm32MTm6ahjPtoi8qyRZBa3jPNo4bZjRY02Wcq/DSHzdOs2bwElVEF9KKTgT+S66G/Xdzi/81g6RlSpk=
  skip_cleanup: true
  file_glob: true
  file: $TRAVIS_BUILD_DIR/*.ipk
  on:
    tags: true
    all_branches: true
    repo: streumix/vcontrold-for-openwrt
    
